/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reservationchambre;

/**
 *
 * @author micka
 */

import DAO.ReservationDAO;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import javax.swing.table.DefaultTableModel;

import java.util.Date;
import java.time.LocalDate;
import java.text.SimpleDateFormat;
import java.text.ParseException;

import java.time.format.DateTimeParseException;


public class MainComponent_1 extends javax.swing.JFrame {

    /**
     * Creates new form MainComponent
     */
    public MainComponent_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuContenaire = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        reservation_btn = new javax.swing.JButton();
        chambre_btn = new javax.swing.JButton();
        sejour_btn = new javax.swing.JButton();
        cambre_occupe_btn = new javax.swing.JButton();
        MainContainer = new javax.swing.JPanel();
        TableContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        FormContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num_chamb_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_reservation_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nom_client_input = new javax.swing.JTextField();
        date_entree_input = new javax.swing.JTextField();
        action_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nbr_jour_input = new javax.swing.JTextField();
        info_client_label = new javax.swing.JLabel();
        mail_client_input = new javax.swing.JTextField();
        info_client_label1 = new javax.swing.JLabel();
        tel_client_input = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_delete_input = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        recu_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuContenaire.setBackground(new java.awt.Color(0, 51, 51));
        MenuContenaire.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setText("Menu");

        reservation_btn.setText("Reservation");

        chambre_btn.setText("Chambre");

        sejour_btn.setText("Sejour");

        cambre_occupe_btn.setText("Chambres occupees");

        javax.swing.GroupLayout MenuContenaireLayout = new javax.swing.GroupLayout(MenuContenaire);
        MenuContenaire.setLayout(MenuContenaireLayout);
        MenuContenaireLayout.setHorizontalGroup(
            MenuContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuContenaireLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addComponent(reservation_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sejour_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chambre_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cambre_occupe_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuContenaireLayout.setVerticalGroup(
            MenuContenaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuContenaireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(chambre_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservation_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sejour_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambre_occupe_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Numero de chambre", "Date de reservation", "Date d'entree", "Nombre de jour", "Nom du client", "Mail", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reservationTable);

        javax.swing.GroupLayout TableContainerLayout = new javax.swing.GroupLayout(TableContainer);
        TableContainer.setLayout(TableContainerLayout);
        TableContainerLayout.setHorizontalGroup(
            TableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TableContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TableContainerLayout.setVerticalGroup(
            TableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jLabel1.setText("Reservation informations");

        jLabel2.setText("Date de reservation");

        jLabel3.setText("Numero chambre");

        jLabel4.setText("Nom du client");

        nom_client_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_client_inputActionPerformed(evt);
            }
        });

        action_btn.setText("Create");
        action_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_btnActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre de jour");

        jLabel10.setText("Date d'entree");

        nbr_jour_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbr_jour_inputActionPerformed(evt);
            }
        });

        info_client_label.setText("Telephone");

        mail_client_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_client_inputActionPerformed(evt);
            }
        });

        info_client_label1.setText("Adresse mail");

        tel_client_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_client_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormContainerLayout = new javax.swing.GroupLayout(FormContainer);
        FormContainer.setLayout(FormContainerLayout);
        FormContainerLayout.setHorizontalGroup(
            FormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormContainerLayout.createSequentialGroup()
                .addGroup(FormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom_client_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nbr_jour_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mail_client_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date_entree_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date_reservation_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(num_chamb_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(FormContainerLayout.createSequentialGroup()
                        .addGroup(FormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(info_client_label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormContainerLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(action_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(FormContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormContainerLayout.createSequentialGroup()
                        .addComponent(info_client_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tel_client_input, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        FormContainerLayout.setVerticalGroup(
            FormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(num_chamb_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_reservation_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_entree_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbr_jour_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(nom_client_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_client_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mail_client_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_client_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tel_client_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(action_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setText("Suppression");

        jLabel7.setText("Identifiant");

        delete_btn.setText("Delete");
        delete_btn.setEnabled(false);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(id_delete_input, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id_delete_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        recu_btn.setText("RECU");
        recu_btn.setEnabled(false);

        javax.swing.GroupLayout MainContainerLayout = new javax.swing.GroupLayout(MainContainer);
        MainContainer.setLayout(MainContainerLayout);
        MainContainerLayout.setHorizontalGroup(
            MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainContainerLayout.createSequentialGroup()
                .addGroup(MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainContainerLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refresh_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(recu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)))
                .addComponent(FormContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        MainContainerLayout.setVerticalGroup(
            MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainContainerLayout.createSequentialGroup()
                        .addComponent(FormContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MainContainerLayout.createSequentialGroup()
                        .addComponent(TableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainContainerLayout.createSequentialGroup()
                                .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(recu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(MainContainerLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MenuContenaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuContenaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nom_client_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_client_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_client_inputActionPerformed

    private void action_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_btnActionPerformed
        // TODO add your handling code here:
        
        ReservationDAO reservation = new ReservationDAO();
        String numCh = num_chamb_input.getText();
        String dateRev = date_reservation_input.getText();
        String dateEntre = date_entree_input.getText();
        int nbrJ = Integer.parseInt(nbr_jour_input.getText().toString());
        String nomCli = nom_client_input.getText();
        String mail = mail_client_input.getText();
        String telephone = tel_client_input.getText();
        
        reservation.setAttribut(numCh, nbrJ, convertToDate(dateRev), convertToDate(dateEntre), nomCli, mail, telephone);
        
        //Le label du btn determine l'action a faire
        String labelBtn = action_btn.getText();
        if(labelBtn == "Create"){
            reservation.create();
            cleanInput();
        }else {
            reservation.update(id);
            action_btn.setText("Create");
        }
        
        //cleanInput();
        
        refresh_btnActionPerformed(evt);
    }//GEN-LAST:event_action_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        ReservationDAO reservation = new ReservationDAO();
        ResultSet result = reservation.getAll();
        DefaultTableModel model = (DefaultTableModel) reservationTable.getModel();
        model.setRowCount(0);
        try{
            while (result.next()) {
                
                // Accéder aux colonnes des résultats
                int idRev = result.getInt("idReserve");
                String numChambr = result.getString("numChambr");
                String dR = result.getString("dateReserve");
                String dE = result.getString("dateEntree");
                int nJ = result.getInt("nbrJour");
                String nomClient = result.getString("nomClient");
                String mail = result.getString("mail");
                String tel = result.getString("telephone");
                
                Object[] rowData = {idRev, numChambr, dR, dE, nJ, nomClient, mail, tel};
                model.addRow(rowData);
            }
            model.fireTableDataChanged();
            action_btn.setText("Create");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        ReservationDAO reservation = new ReservationDAO();
        int idR = Integer.parseInt(id_delete_input.getText().toString());
        reservation.delete(idR);
        id_delete_input.setText("");
        action_btn.setText("Create");
        refresh_btnActionPerformed(evt);
    }//GEN-LAST:event_delete_btnActionPerformed

    private void nbr_jour_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbr_jour_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbr_jour_inputActionPerformed

    private void mail_client_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_client_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mail_client_inputActionPerformed

    private void tel_client_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_client_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_client_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainComponent_1 myComponent = new MainComponent_1();
                myComponent.setVisible(true);
                myComponent.setupTableSelectionListener();
            }
        });
    }
    
    public void setupTableSelectionListener() {
        reservationTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && reservationTable.getSelectedRow() != -1) {
                    action_btn.setText("Update");
                    delete_btn.setEnabled(true);
                    
                    id = Integer.parseInt(reservationTable.getValueAt(reservationTable.getSelectedRow(), 0).toString());
                    numChambr = reservationTable.getValueAt(reservationTable.getSelectedRow(), 1).toString();
                    dateReserve = reservationTable.getValueAt(reservationTable.getSelectedRow(), 2).toString();
                    dateEntree = reservationTable.getValueAt(reservationTable.getSelectedRow(), 3).toString();
                    nbrJour = Integer.parseInt(reservationTable.getValueAt(reservationTable.getSelectedRow(), 4).toString());
                    nomClient = reservationTable.getValueAt(reservationTable.getSelectedRow(), 5).toString();
                    mail = reservationTable.getValueAt(reservationTable.getSelectedRow(), 6).toString();
                    telephone = reservationTable.getValueAt(reservationTable.getSelectedRow(), 7).toString();
                    setInput();
                    
                }
            }
        });
    }
    
    public void cleanInput(){
        num_chamb_input.setText("");
        nbr_jour_input.setText("");
        date_reservation_input.setText("");
        date_entree_input.setText("");
        nom_client_input.setText("");
        mail_client_input.setText("");
        tel_client_input.setText("");
    }
    
    public void setInput(){
        num_chamb_input.setText(numChambr);
        String tmp = String.valueOf(nbrJour);
        nbr_jour_input.setText(tmp);
        date_reservation_input.setText(dateReserve);
        date_entree_input.setText(dateEntree);
        nom_client_input.setText(nomClient);
        mail_client_input.setText(mail);
        tel_client_input.setText(telephone);
        
        tmp = String.valueOf(id);
        id_delete_input.setText(tmp);
    }
    
    public java.sql.Date convertToDate(String tmp){
        java.sql.Date sqlDate = null;
        SimpleDateFormat sourceFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat targetFormat = new SimpleDateFormat("yyyy-MM-dd");
        try{
            java.util.Date dateText= sourceFormat.parse(tmp);
            String formattedDate = targetFormat.format(dateText);
            sqlDate = java.sql.Date.valueOf(formattedDate);
        }catch(ParseException e){
            System.out.println("Erreur de format de date : " + e.getMessage());
        }
        return sqlDate;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormContainer;
    private javax.swing.JPanel MainContainer;
    private javax.swing.JPanel MenuContenaire;
    private javax.swing.JPanel TableContainer;
    private javax.swing.JButton action_btn;
    private javax.swing.JButton cambre_occupe_btn;
    private javax.swing.JButton chambre_btn;
    private javax.swing.JTextField date_entree_input;
    private javax.swing.JTextField date_reservation_input;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField id_delete_input;
    private javax.swing.JLabel info_client_label;
    private javax.swing.JLabel info_client_label1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail_client_input;
    private javax.swing.JTextField nbr_jour_input;
    private javax.swing.JTextField nom_client_input;
    private javax.swing.JTextField num_chamb_input;
    private javax.swing.JButton recu_btn;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTable reservationTable;
    private javax.swing.JButton reservation_btn;
    private javax.swing.JButton sejour_btn;
    private javax.swing.JTextField tel_client_input;
    // End of variables declaration//GEN-END:variables

    
    private int id;
    private String numChambr;
    private int nbrJour;
    private String dateReserve;
    private String dateEntree;
    private String nomClient;
    private String mail;
    private String telephone;
}
